adding clean parameter for git clone or pull target

diff --git a/makefile_common.inc b/makefile_common.inc
--- a/makefile_common.inc
+++ b/makefile_common.inc
@@ -55,31 +55,39 @@ download_file:
 		fi; \
 	fi
 
-# git clone or pull repo, depending if its already exists or not
+# git clone or pull repo, depending if it already exists or not
 # GIT_REPO_URL := https://github.com/example/myrepo.git
 # TARGET_DIR := ./path/to/dir # must be relative to THIS dir
-# TO_GITIGNORE (optional) if you want to put the cloned dir into parents .gitignore file
+# TO_GITIGNORE (optional) if you want to put the cloned dir into parent's .gitignore file
+# CLEAN (optional) if set to "true", cleans up the directory before pulling
 
 # example: $(MAKE) git-clone-or-pull GIT_REPO_URL=https://github.com/OliPelz/makefile-libs.git TARGET_DIR=makefiles_inc
-# to enable with gitignore:  $(MAKE) git-clone-or-pull GIT_REPO_URL=https://github.com/OliPelz/makefile-libs.git TARGET_DIR=makefiles_inc TO_GITIGNORE=true
+# to enable with gitignore: $(MAKE) git-clone-or-pull GIT_REPO_URL=https://github.com/OliPelz/makefile-libs.git TARGET_DIR=makefiles_inc TO_GITIGNORE=true
+# to enable with cleanup: $(MAKE) git-clone-or-pull GIT_REPO_URL=https://github.com/OliPelz/makefile-libs.git TARGET_DIR=makefiles_inc CLEAN=true
 
 # remove trailing ./ from dir
 CLEANED_TARGET_DIR := $(patsubst ./%,%,$(TARGET_DIR))
 
 git-clone-or-pull:
-	@org_repo_name=$$(basename "$(GIT_REPO_URL)" .git); \
-	repo_dir=$${TARGET_DIR:-$$org_repo_name}; \
-	enable_gitignore=$${TO_GITIGNORE:-false}; \
-	if [ -d "$$repo_dir" ]; then \
-		echo "Repository '$$org_repo_name' already exists. Pulling latest changes..."; \
-		(cd "$$repo_dir" && git pull > /dev/null); \
-	else \
-		echo "Cloning repository '$$org_repo_name' into '$(TARGET_DIR)'..."; \
-		git clone "$(GIT_REPO_URL)" "$$repo_dir"; \
-	fi; \
-	if [ "$$enable_gitignore" == "true" ]; then \
-       [ -f .gitignore ] && grep -q '^$(CLEANED_TARGET_DIR)$$' .gitignore || echo '$(CLEANED_TARGET_DIR)' >> .gitignore; \
-	fi;
+        @org_repo_name=$$(basename "$(GIT_REPO_URL)" .git); \
+        repo_dir=$${TARGET_DIR:-$$org_repo_name}; \
+        enable_gitignore=$${TO_GITIGNORE:-false}; \
+        clean_up=$${CLEAN:-false}; \
+        if [ -d "$$repo_dir" ]; then \
+                echo "Repository '$$org_repo_name' already exists."; \
+                if [ "$$clean_up" == "true" ]; then \
+                    echo "Cleaning up repository directory before pulling..."; \
+                    (cd "$$repo_dir" && git clean -fd && git reset --hard); \
+                fi; \
+                echo "Pulling latest changes..."; \
+                (cd "$$repo_dir" && git pull > /dev/null); \
+        else \
+                echo "Cloning repository '$$org_repo_name' into '$(TARGET_DIR)'..."; \
+                git clone "$(GIT_REPO_URL)" "$$repo_dir"; \
+        fi; \
+        if [ "$$enable_gitignore" == "true" ]; then \
+                [ -f .gitignore ] && grep -q '^$(CLEANED_TARGET_DIR)$$' .gitignore || echo '$(CLEANED_TARGET_DIR)' >> .gitignore; \
+        fi;
 
 
 # Sparse Checkout: This feature allows you to only check out a specific part of the repository
