refactor

diff --git a/__make_script_examples/0000_starthere_gatekeeper.sh.template b/__make_script_examples/0000_starthere_gatekeeper.sh.template
--- a/__make_script_examples/0000_starthere_gatekeeper.sh.template
+++ b/__make_script_examples/0000_starthere_gatekeeper.sh.template
@@ -26,14 +26,14 @@ temp_test_env_variable_defined() {
 }
 has_errors=false
 # first check before sourcing
-if ! temp_test_env_variable_defined DOTFILES_REPO_FULL_PATH; then
+if ! temp_test_env_variable_defined THIS_FULL_PATH; then
     abort_color="\033[1;95m" # same as in my colored.sh file for ABORT log event
-    echo -e "${abort_color}[ABORT]\033[0m check failed, mandantory environment variable DOTFILES_REPO_FULL_PATH is not defined, bailing out"
+    echo -e "${abort_color}[ABORT]\033[0m check failed, mandantory environment variable THIS_FULL_PATH is not defined, bailing out"
 	has_error=true
 	exit 1
 fi
 # now source our external functions
-source ${DOTFILES_REPO_FULL_PATH}/external-deps/public-shell-functions/build/__full-source.bash
+source ${THIS_FULL_PATH}/external-deps/public-shell-functions/build/__full-source.bash
 
 log_info2 ">>> PROCESSING 0000_starthere_gatekeeper.sh"
 
