switching from yaml and yq to pure bash

diff --git a/__make_script_examples/0000_starthere_gatekeeper.sh.template b/__make_script_examples/0000_starthere_gatekeeper.sh.template
--- a/__make_script_examples/0000_starthere_gatekeeper.sh.template
+++ b/__make_script_examples/0000_starthere_gatekeeper.sh.template
@@ -60,24 +60,24 @@ fi
 
 
 
-if ! check_command_installed yq; then
-	log_error "check failed, mandantory command yq is not in PATH, bailing out" 
-	has_error=true
-fi
+#if ! check_command_installed yq; then
+#	log_error "check failed, mandantory command yq is not in PATH, bailing out" 
+#	has_error=true
+#fi
 
 if [ "${has_error}" == "true" ]; then
 	exit 1
 fi
 
-if file $(which yq) | grep -q Python; then
-	log_error "please install binary version of yq, not python script, downlord from: https://github.com/mikefarah/yq"
-	exit 1
+#if file $(which yq) | grep -q Python; then
+#	log_error "please install binary version of yq, not python script, downlord from: https://github.com/mikefarah/yq"
+#	exit 1
+#
+#fi
 
-fi
-
-if check_command_installed yq && ! yq ".name" "$PROVISIONING_CONFIG_FULL_PATH" 2>&1 1>/dev/null; then
-	log_error "check failed, mandantory field .name in $PROVISIONING_CONFIG_FULL_PATH missing" 
-	exit 1
-fi
+#if check_command_installed yq && ! yq ".name" "$PROVISIONING_CONFIG_FULL_PATH" 2>&1 1>/dev/null; then
+#	log_error "check failed, mandantory field .name in $PROVISIONING_CONFIG_FULL_PATH missing" 
+#	exit 1
+#fi
 log_info "all tests passed"
 exit 0
diff --git a/__make_script_examples/0001_check_requirements.sh.template b/__make_script_examples/0001_check_requirements.sh.template
--- a/__make_script_examples/0001_check_requirements.sh.template
+++ b/__make_script_examples/0001_check_requirements.sh.template
@@ -7,54 +7,49 @@
 # first source our external functions
 source ${THIS_REPO_FULL_PATH}/external-deps/utility-scripts/build/__full-source.bash
 
+# source our main config file
+source ${THIS_REPO_FULL_PATH}/__config_file/main.sh
+
 log_info2 ">>> PROCESSING 0001_check_requirements.sh"
-
-
-# mandantory
-environment_name=$(parse_yaml ".name" "$PROVISIONING_CONFIG_FULL_PATH")
-
-# optional
-
-# Parse the YAML file to extract the system_packages for the current environment
-system_packages=$(parse_yaml ".system_packages[]" "$PROVISIONING_CONFIG_FULL_PATH" 2>/dev/null)
-
-# Parse the YAML file to extract the other_checks_shell for the current environment
-other_checks_shell=$(parse_yaml ".other_checks_shell[]" "$PROVISIONING_CONFIG_FULL_PATH" 2>/dev/null)
-
 
 failed=false
 
-# Check if the required system packages are installed
-if test_env_variable_defined "system_packages"; then
-    log_info "Checking if system packages are installed for environment: $environment_name"
-    while IFS= read -r package; do
-        log_info "Checking if cmd is available '$package': "
-        if check_command_installed "$package"; then
-            log_info "...Installed"
-        else
-            log_error "...Not installed"
-			failed=true
-        fi
-    done <<< "$system_packages"
+log_info "Checking if system packages are installed for environment: $ENVIRONMENT_NAME"
+
+if ! is_array_defined_nonempty "SYSTEM_PACKAGES"; then
+    log_info "No system packages to install because SYSTEM_PACKAGES is not defined or empty"
 else
-    log_info "No system packages to check for environment: $environment_name"
+    log_info "Installing system checks for environment: $ENVIRONMENT_NAME"
 fi
 
-# Perform other checks using shell commands
-if test_env_variable_defined "other_checks_shell"; then
-    log_info "Running additional checks for environment: $environment_name"
-    while IFS= read -r check_command; do
-        log_info "Executing: ${check_command}"
-        if eval "${check_command}"; then
-			log_info "...Succeeded"
-		else
-			log_error "...Failed"
-			failed=true
-		fi
-    done <<< "${other_checks_shell}"
+
+for PACKAGE in "${SYSTEM_PACKAGES[@]}"; do
+    log_info "Checking if cmd is available '$PACKAGE': "
+    if check_command_installed "$PACKAGE"; then
+        log_info "...Installed"
+    else
+        log_error "...Not installed"
+        failed=true
+    fi
+done
+
+if ! is_array_defined_nonempty "OTHER_SHELL_CHECKS"; then
+    log_info "No additional checks to perform for environment: $ENVIRONMENT_NAME"
 else
-    log_info "No additional checks to perform for environment: $environment_name"
+    log_info "Running additional checks for environment: $ENVIRONMENT_NAME"
 fi
+
+
+# Perform other checks using shell commands
+for CMD in "${OTHER_SHELL_CHECKS[@]}"; do
+    log_info "Executing: '${CMD}'"
+    if eval "${CMD}"; then
+        log_info "...Succeeded"
+    else
+        log_error "...Failed"
+        failed=true
+    fi
+done
 
 if [ "${failed}" == "true" ]; then
 	exit 1
diff --git a/__make_script_examples/0002_pre_create_dirs.sh.template b/__make_script_examples/0002_pre_create_dirs.sh.template
--- a/__make_script_examples/0002_pre_create_dirs.sh.template
+++ b/__make_script_examples/0002_pre_create_dirs.sh.template
@@ -5,28 +5,29 @@
 # first source our external functions
 source ${THIS_REPO_FULL_PATH}/external-deps/utility-scripts/build/__full-source.bash
 
+# source our main config file
+source ${THIS_REPO_FULL_PATH}/__config_file/main.sh
+
 log_info2 ">>> PROCESSING 0002_pre_create_dirs.sh"
-
-# mandantory
-environment_name=$(parse_yaml ".name" "$PROVISIONING_CONFIG_FULL_PATH")
-
-create_dirs=$(parse_yaml ".pre_create_dirs[]" "$PROVISIONING_CONFIG_FULL_PATH" 2>/dev/null)
 
 failed=false
 
-if test_env_variable_defined "create_dirs"; then
-    log_info "Pre-step creating dirs for ${environment_name}"
-    while IFS= read -r create_dir; do
-        log_info "Executing: mkdir ${create_dir}"
-        if eval "mkdir -p ${create_dir}"; then
-	    log_info "...Succeeded"
-        else
-	    log_error "...Failed"
-	    failed=true
-       fi
-    done <<< "${create_dirs}"
+if ! is_array_defined_nonempty "CREATE_DIRS"; then
+    log_info "No dirs to create because SYSTEM_PACKAGES is not defined or empty"
 else
-    log_info "No dirs to create found for environment: $environment_name"
+    log_info "Creating dirs for environment: $ENVIRONMENT_NAME"
+fi
+
+
+for create_dir in "${CREATE_DIRS[@]}"; do
+    log_info "Executing: mkdir ${create_dir}"
+    if eval "mkdir -p ${create_dir}"; then
+        log_info "...Succeeded"
+    else
+        log_error "...Failed"
+        failed=true
+done
+
 fi
 
 if [ "${failed}" == "true" ]; then
diff --git a/__make_script_examples/0003_download_external_dependencies.sh.template b/__make_script_examples/0003_download_external_dependencies.sh.template
--- a/__make_script_examples/0003_download_external_dependencies.sh.template
+++ b/__make_script_examples/0003_download_external_dependencies.sh.template
@@ -6,32 +6,29 @@
 # first source our external functions
 source ${THIS_REPO_FULL_PATH}/external-deps/utility-scripts/build/__full-source.bash
 
+# source our config file
+source ${THIS_REPO_FULL_PATH}/__config_file/main.sh
+
 log_info2 ">>> PROCESSING 0003_download_external_dependencies.sh"
-
-# mandantory
-environment_name=$(parse_yaml ".name" "$PROVISIONING_CONFIG_FULL_PATH")
-
-# optional
-
-# Parse the YAML file to extract important values for the current environment
-#  extracts the name, url and path from each element in the external_dependency_repos array and outputs them as separate lines.
-external_dependency_repos=$(parse_yaml  '.external_dependency_repos[] | .name + "|" + .url + "|" + .path ' "$PROVISIONING_CONFIG_FULL_PATH" 2>/dev/null)
-
 
 failed=false
 
-# Check if the required system packages are installed
-if test_env_variable_defined "external_dependency_repos"; then
-    log_info "installing external dependency git repos into our dotfiles env: $environment_name"
-    
-    while IFS='|' read -r name url path; do
-        # Check if the directory already exists
-	    log_info "cloning ${name} from repo ${repo} to ${path}"
-            git_clone_or_pull --repo_url "$url" --target_dir "$path" --clean && echo "Cloned $url to $path" || failed=true
-    done <<< "${external_dependency_repos}"
+if ! is_array_defined_nonempty "EXTERNAL_DEPENDENCY_REPOS"; then
+    log_info "No dirs to create because SYSTEM_PACKAGES is not defined or empty"
 else
-    log_info "Could not find any external git repos to install: $environment_name"
+    log_info "Managing external depencencies for environment: $ENVIRONMENT_NAME"
 fi
+
+
+for repo_dict in "${EXTERNAL_DEPENDENCY_REPOS[@]}"; do
+	log_info "cloning ${name} from repo ${repo} to ${path}"
+    name=$(array_of_dict_parse_entry "$entry" "name")
+    url=$(array_of_dict_parse_entry "$entry" "repo")
+    path=$(array_of_dict_parse_entry "$entry" "path")
+
+    git_clone_or_pull --repo_url "$url" --target_dir "$path" --clean && echo "Cloned $url to $path" || failed=true
+    failed=true
+done
 
 if [ "${failed}" == "true" ]; then
 	exit 1
